db:
  host: DB_HOST
  port: DB_PORT
  user_id: DB_USERNAME
  password: DB_PASSWORD
  name: DB_NAME
session:
  name: SESSION_NAME
  secret: SESSION_SECRET
  cookie:
    path: SESSION_COOKIE_PATH
    secure: SESSION_COOKIE_SECURE
  store:
    table: SESSION_TABLE_NAME
s3:
  original:
    bucket_name: S3_BUCKET_NAME_ORIGINAL
  thumbnail:
    bucket_name: S3_BUCKET_NAME_THUMBNAIL
