db:
  host: localhost
  port: 3306
  user_id: root
  password: root
  name: mydb
session:
  name: login.session
  secret: login.session,
  cookie:
    path: /
    secure: false
  store:
    table: session-table
s3:
  bucket_name: cupper-hj-test
image:
  upload:
    dir: public/uploads
  thumbnail:
    dir: public/thumbnail
logger:
  file: logs/application.log
