region: us-east-1
server:
  port: 3000
  host: localhost
db:
  host: localhost
  port: 3306
  username: docker
  password: docker
  database: mydb
session:
  name: login.session
  secret: login.session,
  cookie:
    path: /
    secure: false
  store:
    table: session-table
s3:
  original:
    bucket: 'hj-202208-image-original'
  thumbnail:
    bucket: 'hj-202208-image-thumbnail'
image:
  upload:
    dir: public/uploads
logger:
  file: logs/application.log
request_logger:
  file: logs/access.log
