CREATE TABLE user (
  id          INTEGER AUTO_INCREMENT,
  user_id     VARCHAR(50) NOT NULL,
  password    VARCHAR(100) NOT NULL,
  name        VARCHAR(100) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE word (
  id          INT NOT NULL AUTO_INCREMENT,
  content     VARCHAR(50) NOT NULL,
  created_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
